#ifndef OSMIUM_TAGS_KEY_FILTER_HPP
#define OSMIUM_TAGS_KEY_FILTER_HPP

/*

This file is part of Osmium (http://osmcode.org/libosmium).

Copyright 2013,2014 Jochen Topf <jochen@topf.org> and others (see README).

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

#include <functional>
#include <vector>

#include <boost/iterator/filter_iterator.hpp>

#include <osmium/osm/tag.hpp>

namespace osmium {

    /**
     * @brief Code related to working with OSM tags
     */
    namespace tags {

        class KeyFilter : public std::unary_function<const osmium::Tag&, bool> {

            struct Rule {
                std::string key;
                bool result;

                Rule(bool r, const char* k) :
                    key(k),
                    result(r) {
                }

            };

            std::vector<Rule> m_rules;
            bool m_default_result;

        public:

            typedef boost::filter_iterator<KeyFilter, osmium::TagList::const_iterator> iterator;

            KeyFilter(bool default_result) :
                m_rules(),
                m_default_result(default_result) {
            }

            KeyFilter& add(bool result, const char* key) {
                m_rules.emplace_back(result, key);
                return *this;
            }

            bool operator()(const osmium::Tag& tag) const {
                for (const Rule& rule : m_rules) {
                    if (tag.key() == rule.key) {
                        return rule.result;
                    }
                }
                return m_default_result;
            }

        }; // class KeyFilter

    } // namespace tags

} // namespace osmium

#endif // OSMIUM_TAGS_KEY_FILTER_HPP
