#ifndef OSMIUM_AREA_ASSEMBLER_HPP
#define OSMIUM_AREA_ASSEMBLER_HPP

/*

This file is part of Osmium (http://osmcode.org/osmium).

Copyright 2013,2014 Jochen Topf <jochen@topf.org> and others (see README).

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

#include <algorithm>
#include <iostream>
#include <iterator>
#include <list>
#include <map>
#include <vector>

#include <osmium/memory/buffer.hpp>
#include <osmium/osm/area.hpp>
#include <osmium/osm/builder.hpp>
#include <osmium/osm/location.hpp>
#include <osmium/osm/ostream.hpp>
#include <osmium/osm/relation.hpp>
#include <osmium/tags/key_filter.hpp>

#include <osmium/area/segment.hpp>
#include <osmium/area/problem.hpp>
#include <osmium/area/detail/proto_ring.hpp>

namespace osmium {

    namespace area {

        using osmium::area::detail::ProtoRing;

        /**
         * Assembles area objects from multipolygon relations and their
         * members. This is called by the Collector object after all
         * members have been collected.
         */
        class Assembler {

            // List of problems found when assembling areas
            std::vector<Problem> m_problems {};

            // Enables list of problems to be kept
            bool m_remember_problems { false };

            // Enables debug output to stderr
            bool m_debug { false };

            // The way segments
            std::vector<NodeRefSegment> m_segments;

            // The rings we are building from the way segments
            std::list<ProtoRing> m_rings;

            /**
             * Extract all segments from all ways that make up this
             * multipolygon relation. The segments all have their smaller
             * coordinate at the beginning of the segment. Smaller, in this
             * case, means smaller x coordinate, and if they are the same
             * smaller y coordinate.
             */
            void extract_segments_from_ways(const osmium::Relation& relation, const std::vector<size_t>& members, const osmium::memory::Buffer& in_buffer) {
                auto memit = relation.members().begin();
                for (size_t offset : members) {
                    const osmium::Way& way = in_buffer.get<const osmium::Way>(offset);
                    osmium::NodeRef last_nr;
                    for (osmium::NodeRef nr : way.nodes()) {
                        if (last_nr.location() && last_nr != nr) {
                            m_segments.push_back(NodeRefSegment(last_nr, nr, memit->role(), &way));
                        }
                        last_nr = nr;
                    }
                    ++memit;
                }
            }

            /**
             * Find duplicate segments (ie same start and end point) and
             * remove them. This will always remove pairs of the same
             * segment. So if there are three, for instance, two will be
             * removed and one will be left.
             */
            void find_and_erase_duplicate_segments() {
                while (true) {
                    std::vector<NodeRefSegment>::iterator found = std::adjacent_find(m_segments.begin(), m_segments.end());
                    if (found == m_segments.end()) {
                        break;
                    }
                    if (m_debug) {
                        std::cerr << "  erase duplicate segment: " << *found << "\n";
                    }
                    m_segments.erase(found, found+2);
                }
            }

            /**
             * Find intersection between segments.
             *
             * @returns true if there are intersections.
             */
            bool find_intersections() {
                if (m_segments.begin() == m_segments.end()) {
                    return false;
                }

                bool found_intersections = false;

                for (auto it1 = m_segments.begin(); it1 != m_segments.end()-1; ++it1) {
                    const NodeRefSegment& s1 = *it1;
                    for (auto it2 = it1+1; it2 != m_segments.end(); ++it2) {
                        const NodeRefSegment& s2 = *it2;
                        if (s1 == s2) {
                            if (m_debug) {
                                std::cerr << "  found overlap on segment " << s1 << "\n";
                            }
                        } else {
                            if (outside_x_range(s2, s1)) {
                                break;
                            }
                            if (y_range_overlap(s1, s2)) {
                                osmium::Location intersection = calculate_intersection(s1, s2);
                                if (intersection) {
                                    found_intersections = true;
                                    if (m_debug) {
                                        std::cerr << "  segments " << s1 << " and " << s2 << " intersecting at " << intersection << "\n";
                                    }
                                    if (m_remember_problems) {
                                        m_problems.emplace_back(Problem(osmium::area::Problem::problem_type::intersection, osmium::NodeRef(0, intersection), s1, s2));
                                    }
                                }
                            }
                        }
                    }
                }

                return found_intersections;
            }

            /**
             * Initialize area attributes and tags from the attributes and tags
             * of the relation.
             */
            void initialize_area_from_relation(osmium::osm::AreaBuilder& builder, const osmium::Relation& relation) const {
                osmium::Area& area = builder.object();
                area.id(relation.id() * 2 + 1);
                area.version(relation.version());
                area.changeset(relation.changeset());
                area.timestamp(relation.timestamp());
                area.visible(relation.visible());
                area.uid(relation.uid());

                builder.add_user(relation.user());
            }

            void add_tags_to_area(osmium::osm::AreaBuilder& builder, const osmium::Relation& relation, std::vector<ProtoRing*>& outer_rings) const {
                osmium::tags::KeyFilter filter(true);
                filter.add(false, "type").add(false, "created_by").add(false, "source").add(false, "note");

                osmium::tags::KeyFilter::iterator fi_begin(filter, relation.tags().begin(), relation.tags().end());
                osmium::tags::KeyFilter::iterator fi_end(filter, relation.tags().end(), relation.tags().end());

                size_t count = std::distance(fi_begin, fi_end);

                if (m_debug) {
                    std::cerr << "  found " << count << " tags on relation (without ignored ones)\n";
                }

                if (count > 0) {
                    if (m_debug) {
                        std::cerr << "    use tags from relation\n";
                    }
                    osmium::osm::TagListBuilder tl_builder(builder.buffer(), &builder);
                    for (const osmium::Tag& tag : relation.tags()) {
                        tl_builder.add_tag(tag.key(), tag.value());
                    }
                } else {
                    if (m_debug) {
                        std::cerr << "    use tags from outer ways\n";
                    }
                    std::set<const osmium::Way*> ways;
                    for (auto& ring : outer_rings) {
                        ring->get_ways(ways);
                    }
                    if (ways.size() == 1) {
                        if (m_debug) {
                            std::cerr << "      only one outer ways\n";
                        }
                        osmium::osm::TagListBuilder tl_builder(builder.buffer(), &builder);
                        for (const osmium::Tag& tag : (*ways.begin())->tags()) {
                            tl_builder.add_tag(tag.key(), tag.value());
                        }
                    } else {
                        if (m_debug) {
                            std::cerr << "      multiple outer ways, get common tags\n";
                        }
                    }
                }
            }

            /**
             * Go through all the rings and find rings that are not closed.
             * Problem objects are created for the end points of the open
             * rings and placed into the m_problems collection.
             *
             * @returns true if any rings were not closed, false otherwise
             */
            bool check_for_open_rings() {
                bool open_rings = false;

                for (auto& ring : m_rings) {
                    if (!ring.closed()) {
                        open_rings = true;
                        if (m_remember_problems) {
                            m_problems.emplace_back(Problem(osmium::area::Problem::problem_type::ring_not_closed, ring.first_segment().first()));
                            m_problems.emplace_back(Problem(osmium::area::Problem::problem_type::ring_not_closed, ring.last_segment().second()));
                        }
                    }
                }

                return open_rings;
            }

            /**
             * Check whether there are any rings that can be combined with the
             * given ring to one larger ring by appending the other ring to
             * the end of this ring.
             * If the rings can be combined they are and the function returns
             * true.
             */
            bool possibly_combine_rings_end(ProtoRing& ring) {
                osmium::Location location = ring.last_segment().second().location();

                if (m_debug) {
                    std::cerr << "      combine_rings_end\n";
                }
                for (auto it = m_rings.begin(); it != m_rings.end(); ++it) {
                    if (&*it != &ring && !it->closed()) {
                        if ((location == it->first_segment().first().location())) {
                            if (m_debug) {
                                std::cerr << "      ring.last=it->first\n";
                            }
                            ring.merge_ring(*it, m_debug);
                            m_rings.erase(it);
                            return true;
                        }
                        if ((location == it->last_segment().second().location())) {
                            if (m_debug) {
                                std::cerr << "      ring.last=it->last\n";
                            }
                            ring.merge_ring_reverse(*it, m_debug);
                            m_rings.erase(it);
                            return true;
                        }
                    }
                }
                return false;
            }

            /**
             * Check whether there are any rings that can be combined with the
             * given ring to one larger ring by prepending the other ring to
             * the start of this ring.
             * If the rings can be combined they are and the function returns
             * true.
             */
            bool possibly_combine_rings_start(ProtoRing& ring) {
                osmium::Location location = ring.first_segment().first().location();

                if (m_debug) {
                    std::cerr << "      combine_rings_start\n";
                }
                for (auto it = m_rings.begin(); it != m_rings.end(); ++it) {
                    if (&*it != &ring && !it->closed()) {
                        if ((location == it->last_segment().second().location())) {
                            if (m_debug) {
                                std::cerr << "      ring.first=it->last\n";
                            }
                            ring.swap_segments(*it);
                            ring.merge_ring(*it, m_debug);
                            m_rings.erase(it);
                            return true;
                        }
                        if ((location == it->first_segment().first().location())) { // XXX
                            if (m_debug) {
                                std::cerr << "      ring.first=it->first\n";
                            }
                            ring.reverse();
                            ring.merge_ring(*it, m_debug);
                            m_rings.erase(it);
                            return true;
                        }
                    }
                }
                return false;
            }

            bool has_closed_subring_end(ProtoRing& ring, const NodeRefSegment& segment) {
                if (ring.segments().size() < 3) {
                    return false;
                }
                if (m_debug) {
                    std::cerr << "      has_closed_subring_end()\n";
                }
                osmium::Location loc = segment.second().location();
                auto end = ring.segments().end();
                for (auto it = ring.segments().begin() + 1; it != end - 1; ++it) {
                    if (it->first().location() == loc) {
                        if (m_debug) {
                            std::cerr << "        subring found at: " << *it << "\n";
                        }
                        ProtoRing new_ring(it, end);
                        ring.remove_segments(it, end);
                        if (m_debug) {
                            std::cerr << "        split into two rings:\n";
                            std::cerr << "          " << new_ring << "\n";
                            std::cerr << "          " << ring << "\n";
                        }
                        m_rings.emplace_back(new_ring);
                        return true;
                    }
                }
                return false;
            }

            bool has_closed_subring_start(ProtoRing& ring, const NodeRefSegment& segment) {
                if (ring.segments().size() < 3) {
                    return false;
                }
                if (m_debug) {
                    std::cerr << "      has_closed_subring_start()\n";
                }
                osmium::Location loc = segment.first().location();
                for (auto it = ring.segments().begin() + 1; it != ring.segments().end() - 1; ++it) {
                    if (it->second().location() == loc) {
                        if (m_debug) {
                            std::cerr << "        subring found at: " << *it << "\n";
                        }
                        ProtoRing new_ring(ring.segments().begin(), it+1);
                        ring.remove_segments(ring.segments().begin(), it+1);
                        if (m_debug) {
                            std::cerr << "        split into two rings:\n";
                            std::cerr << "          " << new_ring << "\n";
                            std::cerr << "          " << ring << "\n";
                        }
                        m_rings.push_back(new_ring);
                        return true;
                    }
                }
                return false;
            }

            bool check_for_closed_subring(ProtoRing& ring) {
                if (m_debug) {
                    std::cerr << "      check_for_closed_subring()\n";
                }

                osmium::area::detail::ProtoRing::segments_type segments(ring.segments().size());
                std::copy(ring.segments().begin(), ring.segments().end(), segments.begin());
                std::sort(segments.begin(), segments.end());
                auto it = std::adjacent_find(segments.begin(), segments.end(), [](const NodeRefSegment& s1, const NodeRefSegment& s2) {
                    return s1.first().location() == s2.first().location();
                });
                if (it == segments.end()) {
                    return false;
                }
                auto r1 = std::find_first_of(ring.segments().begin(), ring.segments().end(), it, it+1);
                assert(r1 != ring.segments().end());
                auto r2 = std::find_first_of(ring.segments().begin(), ring.segments().end(), it+1, it+2);
                assert(r2 != ring.segments().end());

                if (m_debug) {
                    std::cerr << "      found subring in ring " << ring << " at " << it->first() << "\n";
                }

                auto m = std::minmax(r1, r2);

                ProtoRing new_ring(m.first, m.second);
                ring.remove_segments(m.first, m.second);

                if (m_debug) {
                    std::cerr << "        split ring1=" << new_ring << "\n";
                    std::cerr << "        split ring2=" << ring << "\n";
                }

                m_rings.emplace_back(new_ring);

                return true;
            }

            void combine_rings(const NodeRefSegment& segment, ProtoRing& ring, bool at_end) {
                if (m_debug) {
                    std::cerr << " => match at " << (at_end ? "end" : "start") << " of ring\n";
                }

                if (at_end) {
                    ring.add_segment_end(segment);
                    has_closed_subring_end(ring, segment);
                    if (possibly_combine_rings_end(ring)) {
                        check_for_closed_subring(ring);
                    }
                } else {
                    ring.add_segment_start(segment);
                    has_closed_subring_start(ring, segment);
                    if (possibly_combine_rings_start(ring)) {
                        check_for_closed_subring(ring);
                    }
                }
            }

            /**
             * Append each outer ring together with its inner rings to the
             * area in the buffer.
             */
            void add_rings_to_area(osmium::osm::AreaBuilder& builder, const std::vector<ProtoRing*> outer_rings) const {
                for (const ProtoRing* ring : outer_rings) {
                    if (m_debug) {
                        std::cerr << "    ring " << *ring << " is outer\n";
                    }
                    osmium::osm::OuterRingBuilder ring_builder(builder.buffer(), &builder);
                    ring_builder.add_node_ref(ring->first_segment().first());
                    for (auto& segment : ring->segments()) {
                        ring_builder.add_node_ref(segment.second());
                    }
                    for (ProtoRing* inner : ring->inner_rings()) {
                        osmium::osm::InnerRingBuilder ring_builder(builder.buffer(), &builder);
                        ring_builder.add_node_ref(inner->first_segment().first());
                        for (auto& segment : inner->segments()) {
                            ring_builder.add_node_ref(segment.second());
                        }
                    }
                    builder.buffer().commit();
                }
            }

            bool add_to_existing_ring(NodeRefSegment segment) {
                int n=0;
                for (auto& ring : m_rings) {
                    if (m_debug) {
                        std::cerr << "    check against ring " << n << " " << ring;
                    }
                    if (ring.closed()) {
                        if (m_debug) {
                            std::cerr << " => ring CLOSED\n";
                        }
                    } else {
                        if (ring.last_segment().second() == segment.first() ) {
                            combine_rings(segment, ring, true);
                            return true;
                        }
                        if (ring.last_segment().second() == segment.second() ) {
                            segment.swap_locations();
                            combine_rings(segment, ring, true);
                            return true;
                        }
                        if (ring.first_segment().first() == segment.first() ) {
                            segment.swap_locations();
                            combine_rings(segment, ring, false);
                            return true;
                        }
                        if (ring.first_segment().first() == segment.second() ) {
                            combine_rings(segment, ring, false);
                            return true;
                        }
                        if (m_debug) {
                            std::cerr << " => no match\n";
                        }
                    }

                    ++n;
                }
                return false;
            }

            int count_segments(std::vector<NodeRefSegment>::iterator it, std::vector<NodeRefSegment>::iterator end, const osmium::NodeRef& node_ref) {
                if (m_debug) {
                    std::cerr << "    count_segments for " << node_ref << "\n";
                }
                int count = 0;
                while (it != end) {
                    if (m_debug) {
                        std::cerr << "      segments for count: " << *it;
                    }
                    if (it->to_left_of(node_ref.location())) {
                        ++count;
                        if (m_debug) {
                            std::cerr << " counted\n";
                        }
                    } else {
                        if (m_debug) {
                            std::cerr << " not counted\n";
                        }
                    }
                    ++it;
                }
                if (m_debug) {
                    std::cerr << "      count=" << count << "\n";
                }
                return count;
            }

            void check_inner_outer(ProtoRing& ring) {
                const osmium::NodeRef& min_node = ring.min_node();
                osmium::Location min_loc = min_node.location();
                if (m_debug) {
                    std::cerr << "    check_inner_outer min_node=" << min_node << "\n";
                }
                for (auto it = m_segments.begin(); it != m_segments.end(); ++it) {
                    if (it->first().location() == min_loc) {
                        if (count_segments(m_segments.begin(), it, min_node) % 2) {
                            ring.set_inner();
                        }
                        return;
                    }
                    if (it->second().location() == min_loc) {
                        std::cerr << "SECOND loc: " << *it << "\n";
                    }
                }
            }

            void check_inner_outer_roles(std::vector<ProtoRing*>& outer, std::vector<ProtoRing*>& inner) {
                if (m_debug) {
                    std::cerr << "    check_inner_outer_roles\n";
                }
                for (auto ringptr : outer) {
                    for (auto segment : ringptr->segments()) {
                        if (!segment.role_outer()) {
                            std::cerr << "      segment " << segment << " from way " << segment.way()->id() << " should have role 'outer'\n";
                        }
                    }
                }
                for (auto ringptr : inner) {
                    for (auto segment : ringptr->segments()) {
                        if (!segment.role_inner()) {
                            std::cerr << "      segment " << segment << " from way " << segment.way()->id() << " should have role 'inner'\n";
                        }
                    }
                }
            }

        public:

            Assembler() = default;

            ~Assembler() = default;

            /**
             * Enable or disable debug output to stderr. This is for Osmium
             * developers only.
             */
            void enable_debug_output(bool debug=true) {
                m_debug = debug;
            }

            /**
             * Enable or disable collection of problems in the input data.
             * If this is enabled the assembler will keep a list of all
             * problems found (such as self-intersections and unclosed rings).
             * This creates some overhead so it is disabled by default.
             */
            void remember_problems(bool remember=true) {
                m_remember_problems = remember;
            }

            /**
             * Clear the list of problems that have been found.
             */
            void clear_problems() {
                m_problems.clear();
            }

            /**
             * Get the list of problems found so far in the input data.
             */
            const std::vector<Problem>& problems() const {
                return m_problems;
            }

            /**
             * Assemble an area from the given relation and its members.
             * All members are to be found in the in_buffer at the offsets
             * given by the members parameter.
             * The resulting area is put into the out_buffer.
             */
            void operator()(const osmium::Relation& relation, const std::vector<size_t>& members, const osmium::memory::Buffer& in_buffer, osmium::memory::Buffer& out_buffer) {
                m_segments.clear();
                m_rings.clear();

                extract_segments_from_ways(relation, members, in_buffer);

                if (m_debug) {
                    std::cerr << "\nBuild relation id()=" << relation.id() << " members.size()=" << members.size() << " segments.size()=" << m_segments.size() << "\n";
                }

                // Now all of these segments will be sorted from bottom left
                // to top right.
                std::sort(m_segments.begin(), m_segments.end());

                // remove empty segments
/*                m_segments.erase(std::remove_if(m_segments.begin(), m_segments.end(), [](osmium::UndirectedSegment& segment) {
                    return segment.first() == segment.second();
                }));*/

                find_and_erase_duplicate_segments();

                // Now create the Area object and add the attributes and tags
                // from the relation.
                osmium::osm::AreaBuilder builder(out_buffer);
                initialize_area_from_relation(builder, relation);

                // From now on we have an area object without any rings in it.
                // Areas without rings are "defined" to be invalid. We commit
                // this area and the caller of the assembler will see the
                // invalid area. If all goes well, we later add the rings, commit
                // again, and thus make a valid area out of it.
                out_buffer.commit();

                // Now we look for segments crossing each other. If there are
                // any, the multipolygon is invalid.
                // In the future this could be improved by trying to fix those
                // cases.
                if (find_intersections()) {
                    return;
                }

                // Now iterator over all segments and add them to rings. Each segment
                // is tacked on to either end of an existing ring if possible, or a
                // new ring is started with it.
                for (auto it = m_segments.begin(); it != m_segments.end(); ++it) {
                    if (m_debug) {
                        std::cerr << "  checking segment " << *it << "\n";
                    }
                    if (!add_to_existing_ring(*it)) {
                        if (m_debug) {
                            std::cerr << "    new ring for segment " << *it << "\n";
                        }
                        m_rings.emplace_back(ProtoRing(*it));
                    }
                }

                if (m_debug) {
                    std::cerr << "  Rings:\n";
                    for (auto& ring : m_rings) {
                        std::cerr << "    " << ring;
                        if (ring.closed()) {
                            std::cerr << " (closed)";
                        }
                        std::cerr << "\n";
                    }
                }

                if (check_for_open_rings()) {
                    if (m_debug) {
                        std::cerr << "  not all rings are closed\n";
                    }
                    return;
                }

                if (m_debug) {
                    std::cerr << "  Find inner/outer...\n";
                }

                std::vector<ProtoRing*> outer_rings;
                std::vector<ProtoRing*> inner_rings;

                if (m_rings.size() == 1) {
                    outer_rings.push_back(&m_rings.front());
                } else {
                    for (auto& ring : m_rings) {
                        check_inner_outer(ring);
                        if (ring.outer()) {
                            if (!ring.is_cw()) {
                                ring.reverse();
                            }
                            outer_rings.push_back(&ring);
                        } else {
                            if (ring.is_cw()) {
                                ring.reverse();
                            }
                            inner_rings.push_back(&ring);
                        }
                    }

                    if (outer_rings.size() == 1) {
                        for (auto inner : inner_rings) {
                            outer_rings.front()->add_inner_ring(inner);
                        }
                    } else {
                        // sort outer rings by size, smallest first
                        std::sort(outer_rings.begin(), outer_rings.end(), [](ProtoRing* a, ProtoRing* b) {
                            return a->area() < b->area();
                        });
                        for (auto inner : inner_rings) {
                            for (auto outer : outer_rings) {
                                if (inner->is_in(outer)) {
                                    outer->add_inner_ring(inner);
                                    break;
                                }
                            }
                        }
                    }
                }

                check_inner_outer_roles(outer_rings, inner_rings);

                add_tags_to_area(builder, relation, outer_rings);

                add_rings_to_area(builder, outer_rings);
            }

        }; // class Assembler

    } // namespace area

} // namespace osmium

#endif // OSMIUM_AREA_ASSEMBLER_HPP
