#ifndef OSMIUM_INDEX_MAP_MMAP_LIST_HPP
#define OSMIUM_INDEX_MAP_MMAP_LIST_HPP

/*

This file is part of Osmium (http://osmcode.org/osmium).

Copyright 2013 Jochen Topf <jochen@topf.org> and others (see README).

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

#include <stdexcept>

#include <osmium/index/map.hpp>
#include <osmium/detail/typed_mmap.hpp>

namespace osmium {

    namespace index {

        namespace map {

            template <typename TKey, typename TValue>
            class MmapList : public osmium::index::map::Map<TKey, TValue> {

            public:

                typedef typename osmium::index::map::Map<TKey, TValue>::element_type element_type;

            private:

                size_t m_size;
                element_type* m_elements;

            public:

                MmapList(int fd) :
                    m_size(osmium::detail::typed_mmap<element_type>::file_size(fd)),
                    m_elements(osmium::detail::typed_mmap<element_type>::map(m_size, fd)) {
                }

                ~MmapList() {
                    clear();
                }

                void set(const TKey, const TValue) override final {
                    throw std::logic_error("MmapList indexes are read-only");
                }

                const TValue get(const TKey id) const override final {
                    const element_type* it = std::lower_bound(m_elements, m_elements + m_size, element_type(id));
                    if (it != m_elements + m_size && it->key == id) {
                        return it->value;
                    } else {
                        throw std::out_of_range("Unknown ID");
                    }
                }

                size_t size() const override final {
                    return m_size;
                }

                size_t used_memory() const override final {
                    return 0;
                }

                void clear() override final {
                    if (m_elements) {
                        osmium::detail::typed_mmap<element_type>::unmap(m_elements, m_size);
                        m_elements = nullptr;
                        m_size = 0;
                    }
                };

                const element_type* begin() const {
                    return m_elements;
                }

                const element_type* end() const {
                    return m_elements + m_size;
                }

            }; // class MmapList

        } // namespace map

    } // namespace index

} // namespace osmium


#endif // OSMIUM_INDEX_MAP_MMAP_LIST_HPP
