#ifndef OSMIUM_OSM_DIFF_OBJECT_HPP
#define OSMIUM_OSM_DIFF_OBJECT_HPP

/*

This file is part of Osmium (http://osmcode.org/osmium).

Copyright 2013 Jochen Topf <jochen@topf.org> and others (see README).

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

#include <osmium/osm/node.hpp>
#include <osmium/osm/way.hpp>
#include <osmium/osm/relation.hpp>

namespace osmium {

    template <class T>
    class DiffObject {

        const T& m_prev;
        const T& m_curr;
        const T& m_next;

    public:

        DiffObject(const T& prev, const T& curr, const T& next) :
            m_prev(prev),
            m_curr(curr),
            m_next(next) {
        }

        const T& prev() const {
            return m_prev;
        }

        const T& current() const {
            return m_curr;
        }

        const T& next() const {
            return m_next;
        }

        bool first() const {
            return &m_prev == &m_curr;
        }

        bool last() const {
            return &m_curr == &m_next;
        }

        const osmium::object_id_type id() const {
            return m_curr.id();
        }

        const osmium::object_version_type version() const {
            return m_curr.version();
        }

        const osmium::changeset_id_type changeset() const {
            return m_curr.changeset();
        }

        const osmium::Timestamp start_time() const {
            return m_curr.timestamp();
        }

        const osmium::Timestamp end_time() const {
            return last() ? osmium::Timestamp() : m_next.timestamp();
        }

    }; // class DiffObject

    typedef DiffObject<osmium::Node>     DiffNode;
    typedef DiffObject<osmium::Way>      DiffWay;
    typedef DiffObject<osmium::Relation> DiffRelation;

} // namespace osmium

#endif // OSMIUM_OSM_DIFF_OBJECT_HPP
