#ifndef OSMIUM_OSM_OBJECT_COMPARISONS_HPP
#define OSMIUM_OSM_OBJECT_COMPARISONS_HPP

/*

This file is part of Osmium (http://osmcode.org/osmium).

Copyright 2013 Jochen Topf <jochen@topf.org> and others (see README).

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

#include <osmium/osm/object.hpp>

namespace osmium {

    /**
     * Objects can be ordered by type, id and version.
     * Note that we use the absolute value of the id for a
     * better ordering of objects with negative id.
     */
    inline bool operator<(const Object& lhs, const Object& rhs) {
        if (lhs.type() != rhs.type()) {
            return lhs.type() < rhs.type();
        }
        return (lhs.id() == rhs.id() && lhs.version() < rhs.version()) ||
               abs(lhs.id()) < abs(rhs.id());
    }

    /**
     * Objects are equal if their type, id, and version are equal.
     */
    inline bool operator==(const Object& lhs, const Object& rhs) {
        return lhs.type() == rhs.type() &&
               lhs.id() == rhs.id() &&
               lhs.version() == rhs.version();
    }

    namespace osm {

        struct object_equal_type_id_version {

            bool operator()(const Object& lhs, const Object& rhs) {
                return lhs == rhs;
            }

            bool operator()(const Object* lhs, const Object* rhs) {
                return *lhs == *rhs;
            }

        };

        struct object_equal_type_id {

            bool operator()(const Object& lhs, const Object& rhs) {
                return lhs.type() == rhs.type() &&
                       lhs.id() == rhs.id();
            }

            bool operator()(const Object* lhs, const Object* rhs) {
                return lhs->type() == rhs->type() &&
                       lhs->id() == rhs->id();
            }

        };

        struct object_order_type_id_version {

            bool operator()(const Object& lhs, const Object& rhs) {
                return lhs < rhs;
            }

            bool operator()(const Object* lhs, const Object* rhs) {
                return *lhs < *rhs;
            }

        };

        struct object_order_type_id_reverse_version {

            bool operator()(const Object& lhs, const Object& rhs) {
                if (lhs.type() != rhs.type()) {
                    return lhs.type() < rhs.type();
                }
                return (lhs.id() == rhs.id() && lhs.version() > rhs.version()) ||
                       abs(lhs.id()) < abs(rhs.id());
            }

            bool operator()(const Object* lhs, const Object* rhs) {
                if (lhs->type() != rhs->type()) {
                    return lhs->type() < rhs->type();
                }
                return (lhs->id() == rhs->id() && lhs->version() > rhs->version()) ||
                       abs(lhs->id()) < abs(rhs->id());
            }

        };

    } // namespace osm

} // namespace osmium

#endif // OSMIUM_OSM_OBJECT_COMPARISONS_HPP
