#ifndef OSMIUM_GEOM_OGR_HPP
#define OSMIUM_GEOM_OGR_HPP

/*

This file is part of Osmium (http://osmcode.org/osmium).

Copyright 2013 Jochen Topf <jochen@topf.org> and others (see README).

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

#define OSMIUM_COMPILE_WITH_CFLAGS_OGR `gdal-config --cflags`
#define OSMIUM_LINK_WITH_LIBS_OGR `gdal-config --libs`

#include <memory>

#include <ogr_geometry.h>

#include <osmium/osm/node.hpp>
#include <osmium/osm/way.hpp>

namespace osmium {

    /**
     * @brief Namespace for everything related to geometry.
     */
    namespace geom {

        inline std::unique_ptr<OGRPoint> create_ogr_point(const osmium::Location& location) {
            return std::move(std::unique_ptr<OGRPoint>(new OGRPoint(location.lon(), location.lat())));
        }

        inline std::unique_ptr<OGRPoint> create_ogr_point(const osmium::Node& node) {
            return std::move(create_ogr_point(node.location()));
        }

        inline std::unique_ptr<OGRPoint> create_ogr_point(const osmium::WayNode& wn) {
            return std::move(create_ogr_point(wn.location()));
        }

        inline std::unique_ptr<OGRLineString> create_ogr_linestring(const osmium::WayNodeList& wnl, bool reverse = false) {
            std::unique_ptr<OGRLineString> ogr_linestring(new OGRLineString());

            if (reverse) {
                // XXX
            } else {
                osmium::Location last_location;
                for (auto& wn : wnl) {
                    if (last_location != wn.location()) {
                        ogr_linestring->addPoint(wn.location().lon(), wn.location().lat());
                        last_location = wn.location();
                    }
                }
            }

            return std::move(ogr_linestring);
        }

    } // namespace geom

} // namespace osmium


#endif // OSMIUM_GEOM_OGR_HPP
