#ifndef OSMIUM_HANDLER_CHAIN_HPP
#define OSMIUM_HANDLER_CHAIN_HPP

/*

This file is part of Osmium (http://osmcode.org/libosmium).

Copyright 2014 Jochen Topf <jochen@topf.org> and others (see README).

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

#include <tuple>

#include <osmium/handler.hpp>

#define OSMIUM_CHAIN_HANDLER_CALL1(_func_) \
    template <int N, int SIZE, class THandlers> \
    struct call_ ## _func_ { \
        void operator()(THandlers& handlers) { \
            std::get<N>(handlers)._func_(); \
            call_ ## _func_<N+1, SIZE, THandlers>()(handlers); \
        } \
    }; \
    template <int SIZE, class THandlers> \
    struct call_ ## _func_<SIZE, SIZE, THandlers> { \
        void operator()(THandlers& handlers) {} \
    };

#define OSMIUM_CHAIN_HANDLER_CALL2(_func_, _type_) \
    template <int N, int SIZE, class THandlers> \
    struct call_ ## _func_ { \
        void operator()(THandlers& handlers, osmium::_type_& object) { \
            std::get<N>(handlers)._func_(object); \
            call_ ## _func_<N+1, SIZE, THandlers>()(handlers, object); \
        } \
    }; \
    template <int SIZE, class THandlers> \
    struct call_ ## _func_<SIZE, SIZE, THandlers> { \
        void operator()(THandlers& handlers, osmium::_type_&) {} \
    };

namespace osmium {

    namespace handler {

        /**
         * This handler allows chaining of any number of handlers into a single
         * handler.
         */
        template <class ...THandler>
        class ChainHandler : public osmium::handler::Handler {

            typedef std::tuple<THandler&...> handlers_type;
            handlers_type m_handlers;

            OSMIUM_CHAIN_HANDLER_CALL1(init);
            OSMIUM_CHAIN_HANDLER_CALL1(before_nodes);
            OSMIUM_CHAIN_HANDLER_CALL1(after_nodes);
            OSMIUM_CHAIN_HANDLER_CALL1(before_ways);
            OSMIUM_CHAIN_HANDLER_CALL1(after_ways);
            OSMIUM_CHAIN_HANDLER_CALL1(before_relations);
            OSMIUM_CHAIN_HANDLER_CALL1(after_relations);
            OSMIUM_CHAIN_HANDLER_CALL1(before_changesets);
            OSMIUM_CHAIN_HANDLER_CALL1(after_changesets);
            OSMIUM_CHAIN_HANDLER_CALL1(done);

            OSMIUM_CHAIN_HANDLER_CALL2(node, Node);
            OSMIUM_CHAIN_HANDLER_CALL2(way, Way);
            OSMIUM_CHAIN_HANDLER_CALL2(relation, Relation);
            OSMIUM_CHAIN_HANDLER_CALL2(changeset, Changeset);

        public:

            ChainHandler(THandler&... handlers) :
                m_handlers(handlers...) {
            }

            void init() {
                call_init<0, sizeof...(THandler), handlers_type>()(m_handlers);
            }

            void before_nodes() {
                call_before_nodes<0, sizeof...(THandler), handlers_type>()(m_handlers);
            }

            void node(osmium::Node& node) {
                call_node<0, sizeof...(THandler), handlers_type>()(m_handlers, node);
            }

            void after_nodes() {
                call_after_nodes<0, sizeof...(THandler), handlers_type>()(m_handlers);
            }

            void before_ways() {
                call_before_ways<0, sizeof...(THandler), handlers_type>()(m_handlers);
            }

            void way(osmium::Way& way) {
                call_way<0, sizeof...(THandler), handlers_type>()(m_handlers, way);
            }

            void after_ways() {
                call_after_ways<0, sizeof...(THandler), handlers_type>()(m_handlers);
            }

            void before_relations() {
                call_before_relations<0, sizeof...(THandler), handlers_type>()(m_handlers);
            }

            void relation(osmium::Relation& relation) {
                call_relation<0, sizeof...(THandler), handlers_type>()(m_handlers, relation);
            }

            void after_relations() {
                call_after_relations<0, sizeof...(THandler), handlers_type>()(m_handlers);
            }

            void before_changesets()  {
                call_before_changesets<0, sizeof...(THandler), handlers_type>()(m_handlers);
            }

            void changeset( osmium::Changeset& changeset) {
                call_changeset<0, sizeof...(THandler), handlers_type>()(m_handlers, changeset);
            }

            void after_changesets()  {
                call_after_changesets<0, sizeof...(THandler), handlers_type>()(m_handlers);
            }

            void done() {
                call_done<0, sizeof...(THandler), handlers_type>()(m_handlers);
            }

        }; // class ChainHandler

    } // namespace handler

} // namespace osmium

#endif // OSMIUM_HANDLER_CHAIN_HPP
